# ====================================================================
#  DEV ortami - uygulama ayarlari (veritabani: database-dev.properties)
# ====================================================================
# 8080 yerelde Oracle XE, 8081 dolu oldugu icin 8082 secildi.
server.port=8082

logging.level.root=info
logging.level.org.liquibase=info
logging.level.org.springframework.web=info
