# ====================================================================
#  DEV ortami - Yerel PostgreSQL veritabani baglantisi
#  (Ayni baglantiyi DBeaver ile de acabilirsiniz)
# --------------------------------------------------------------------
#  Host : localhost      Port : 5432      DB : interndb
# ====================================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/internStartUp
spring.datasource.jdbcUrl=jdbc:postgresql://localhost:5432/internStartUp
spring.datasource.username=postgres
spring.datasource.password=postgres

# DEV'de SQL loglari
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=debug
